# Generated by Django 4.2.7 on 2026-08-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(max_length=64)),
                ('squarespace_order_id', models.CharField(max_length=128)),
                ('squarespace_line_item_id', models.CharField(max_length=128)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_sales', to='ticketing.show')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSkuMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(max_length=64)),
                ('squarespace_sku', models.CharField(max_length=64)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_sku_map', to='ticketing.show')),
            ],
            options={
                'unique_together': {('show', 'squarespace_sku'), ('show', 'seat_code')},
            },
        ),
        migrations.AddConstraint(
            model_name='seatsale',
            constraint=models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('show', 'seat_code'), name='unique_active_seat_sale'),
        ),
        migrations.AlterUniqueTogether(
            name='seatsale',
            unique_together={('squarespace_order_id', 'squarespace_line_item_id')},
        ),
    ]
