// Seat helpers — keep block grids readable as literals below.
// A() = actor (cast, never for public sale)
// G() = general admission (individually selectable, default price)
// D(label) = delegate seat, assigned to the state given by `label`
function seat(type, opts = {}) {
  return { type, ...opts }
}
const A = () => seat('actor')
const G = () => seat('ga')
const D = (label) => seat('delegate', { label })
const _ = null // no seat here (gap / walkway / non-seat space)

// Each seat is its own Squarespace product (see
// backend/test_data/generate_show_test_data.mjs), grouped into a
// per-show-day Category, so every seat gets a real permalink instead of
// a variant dropdown. This slug is the single source of truth shared by
// the CSV generator (which sets each product's `Product URL` to it) and
// the frontend (which links straight to it) — keep them importing this
// same function so they can't drift apart.
export function seatProductSlug(showSku, seatCode) {
  return `swing-night-${showSku}-${seatCode}`.toLowerCase()
}

export function seatBuyLink(showSku, seatCode) {
  return `${CONFIG.squarespaceBase}/${seatProductSlug(showSku, seatCode)}`
}

export const CONFIG = {
  // Dev: match whatever host served this page, so it also works from a
  // phone on the LAN (see `make dev-lan`). Prod build always uses the
  // literal fallback below — set that to the real Django domain before
  // going live.
  apiBase: import.meta.env?.DEV
    ? `http://${window.location.hostname}:8100`
    : 'http://127.0.0.1:8100', // your Django domain, no trailing slash
  defaultPrice: 25,

  // Your Squarespace site's domain, no trailing slash. Per-seat buy links
  // are computed from this + seatProductSlug() above.
  squarespaceBase: 'https://yoursite.squarespace.com',

  // One entry per performance day. sku must match a Show.sku_prefix in
  // Django.
  shows: [
    { sku: 'SEPT12', label: 'Sat, Sept 12' },
    { sku: 'SEPT13', label: 'Sun, Sept 13' },
    // Test data — Fri/Sat shows Oct 3 - Nov 3 2026, generated by
    // backend/test_data/generate_show_test_data.mjs (keep in sync).
    { sku: 'OCT03', label: 'Sat, October 3, 2026' },
    { sku: 'OCT09', label: 'Fri, October 9, 2026' },
    { sku: 'OCT10', label: 'Sat, October 10, 2026' },
    { sku: 'OCT16', label: 'Fri, October 16, 2026' },
    { sku: 'OCT17', label: 'Sat, October 17, 2026' },
    { sku: 'OCT23', label: 'Fri, October 23, 2026' },
    { sku: 'OCT24', label: 'Sat, October 24, 2026' },
    { sku: 'OCT30', label: 'Fri, October 30, 2026' },
    { sku: 'OCT31', label: 'Sat, October 31, 2026' }
  ],

  // The real room: several distinct seating blocks (some rotated) plus
  // furniture, transcribed from seatchart.png (per-seat type/label) and
  // cross-referenced against seatchart.txt (room envelope, stage/podium,
  // piano ). This is a best-effort transcription —
  // verify against the physical venue before going live.
  //
  // Seat identity: every seat's `code` is derived from its block id + grid
  // position (not its type/label), so reassigning a seat's role later
  // (e.g. which physical seats are "Actor" seats) is just editing that
  // cell's A()/G()/D() in place below — no effect on sold-seat tracking.
  venue: {
    width: 1200,
    height: 900,

    walls: { x: 10, y: 10, w: 1180, h: 880, rx: 12 },

    furniture: [
      { type: 'piano', x: 90, y: 60, w: 150, h: 90, label: 'Grand Piano' },
      { type: 'stage', x: 620, y: 420, w: 200, h: 80, label: 'Stage', podium: { w: 70, h: 34 } },
    ],

    blocks: [
      // Left block — tall, 4 seats across, 11 rows.
      {
        id: 'L',
        x: 40, y: 220, rotation: 0,
        cellSize: 28, gap: 6,
        grid: [
          [G(), A(), A(), G()],
          [D('TX'), G(), G(), G()],
          [G(), G(), D('NM'), A()],
          [D('CO'), G(), G(), D('HI')],
          [G(), G(), G(), G()],
          [D('PHIL'), G(), G(), A()],
          [G(), A(), A(), D('AZ')],
          [G(), A(), G(), G()],
          [D('C.Z.'), G(), G(), G()],
          [G(), D('RI'), G(), D('AK')],
          [A(), G(), D('DE'), A()]
        ]
      },

      // Top-center block — two pairs of columns split by a center aisle
      // (col index 2 stays empty), plus two isolated seats on the far
      // right (col index 5, only populated on rows 1-2).
      {
        id: 'T',
        x: 330, y: 60, rotation: 0,
        cellSize: 28, gap: 6,
        grid: [
          [G(), G(), _, G(), D('SD'), _],
          [A(), D('MN'), _, G(), A(), A()],
          [D('WI'), G(), _, D('MT'), G(), G()],
          [A(), D('WA'), _, G(), D('MI'), _]
        ]
      },

      // Center block, upper half — freestanding, below the top block.
      {
        id: 'M1',
        x: 430, y: 260, rotation: 0,
        cellSize: 28, gap: 6,
        grid: [
          [G(), G(), A(), A()],
          [A(), G(), D('AL'), G()],
          [D('WV'), D('DC'), G(), D('SC')],
          [A(), A(), A(), A()]
        ]
      },

      // Center block, lower half — separated from M1 by a walkway gap.
      {
        id: 'M2',
        x: 430, y: 460, rotation: 0,
        cellSize: 28, gap: 6,
        grid: [
          [D('MD'), A(), G(), _],
          [A(), G(), G(), G()],
          [G(), D('NJ'), D('VT'), A()],
          [D('ME'), G(), A(), A()]
        ]
      },

      // Bottom-center block — mirrors the top block's aisle/isolated-seat
      // layout.
      {
        id: 'B',
        x: 330, y: 650, rotation: 0,
        cellSize: 28, gap: 6,
        grid: [
          [A(), A(), _, D('CT'), D('NH'), A()],
          [G(), A(), _, A(), G(), A()],
          [A(), G(), _, G(), G(), _],
          [D('OR'), G(), G(), G(), A(), D('ID')]
        ]
      },

      // Right-side blocks — rotated to follow the room's angled wall.
      {
        id: 'R1',
        x: 780, y: 150, rotation: -30,
        cellSize: 30, gap: 6,
        grid: [
          [A(), G()],
          [A(), D('UT')],
          [G(), G()],
          [A(), G()]
        ]
      },
      {
        id: 'R2',
        x: 840, y: 390, rotation: 0,
        cellSize: 30, gap: 6,
        grid: [
          [A(), A()],
          [G(), G()],
          [D('NV'), G()],
          [A(), A()]
        ]
      },
      {
        id: 'R3',
        x: 780, y: 630, rotation: 30,
        cellSize: 30, gap: 6,
        grid: [
          [A(), G()],
          [G(), D('VIR IS.')],
          [A(), G()],
          [A(), G()]
        ]
      }
    ]
  }
}

// Flat code -> seat lookup, built once from the static venue layout above.
// code format: "<blockId><row+1>-<col+1>" (1-indexed, e.g. "L2-3") — the
// same friendly, block-scoped string shown to buyers as the seat's label,
// so the SKU/permalink a buyer sees matches the seat identity used
// everywhere else (holds, sold-seat tracking). Still fully derived from
// block id + grid position, not type or delegate state, so reassigning a
// cell's A()/G()/D() in place doesn't affect identity or sold-seat
// tracking. Delegate seats display their assigned state as a separate
// `label` field (see below) but keep this same position-based `code` as
// their actual identity, so two delegate seats can safely share a state
// without colliding.
function buildSeatIndex(venue) {
  const index = new Map()
  const seen = new Map()
  for (const block of venue.blocks) {
    block.grid.forEach((row, r) => {
      row.forEach((cell, c) => {
        if (!cell) return
        const code = seatCode(block.id, r, c)
        if (seen.has(code)) {
          throw new Error(
            `Duplicate seat code "${code}" — blocks ${seen.get(code)} and ${block.id} collide. ` +
              'Adjust block ids so seatCode() output stays unique.'
          )
        }
        seen.set(code, block.id)
        // Delegate seats display their state code; every other seat's
        // display label is just its code (already friendly/unique).
        const label = cell.label || code
        index.set(code, { ...cell, label, code })
      })
    })
  }
  return index
}

export const SEAT_INDEX = buildSeatIndex(CONFIG.venue)

export function seatCode(blockId, row, col) {
  return `${blockId}${row + 1}-${col + 1}`
}
