// Seat helpers — keep block grids readable as literals below.
// A() = actor (cast, never for public sale)
// G() = gallery (individually selectable, no state attached)
// D(label) = delegate seat, assigned to the state/territory given by `label`
// C(label) = state chairperson seat, assigned to the state/territory given
//   by `label` (has lines, unlike a plain delegate seat)
// N(label) = candidate seat, assigned to the named individual given by
//   `label` (shown as initials — the seat's tile color already
//   disambiguates from state delegate/chair labels, so collisions are fine)
function seat(type, opts = {}) {
  return { type, ...opts }
}
const A = () => seat('actor')
const G = () => seat('ga')
const D = (label) => seat('delegate', { label })
const C = (label) => seat('chair', { label })
const N = (name) => seat('candidate', { label: name })
const _ = null // no seat here (gap / walkway / non-seat space)

// Each seat is its own Squarespace product (see
// backend/test_data/generate_show_test_data.mjs), grouped into a
// per-show-day Category, so every seat gets a real permalink instead of
// a variant dropdown. This slug is the single source of truth shared by
// the CSV generator (which sets each product's `Product URL` to it) and
// the frontend (which links straight to it) — keep them importing this
// same function so they can't drift apart.
export function seatProductSlug(showSku, seatCode) {
  return `convention-${showSku}-${seatCode}`.toLowerCase()
}

export function seatBuyLink(showSku, seatCode) {
  return `${CONFIG.squarespaceBase}/${CONFIG.squarespaceProductPage}/p/${seatProductSlug(showSku, seatCode)}`
}

export const CONFIG = {
  // Dev: match whatever host served this page, so it also works from a
  // phone on the LAN (see `make dev-lan`). Prod build always uses the
  // literal fallback below — set that to the real Django domain before
  // going live.
  apiBase: import.meta.env?.DEV
    ? `http://${window.location.hostname}:8100`
    : 'https://seatchart.swseng.io', // stakeholder demo backend
  defaultPrice: 25,

  // Per-tier pricing for the four sellable seat types (actor seats are
  // never sold, so have no entry here). Looked up by App.jsx when
  // computing the selected seat's price — falls back to defaultPrice
  // above for any type not listed here.
  pricesByType: {
    ga: 44,
    delegate: 68,
    chair: 76,
    candidate: 100
  },

  // Your Squarespace site's domain, no trailing slash. Per-seat buy links
  // are computed from this + seatProductSlug() above.
  squarespaceBase: 'https://www.conventionplay.com',

  // Slug of the existing Squarespace Store page products should be
  // imported under (the CSV's `Product Page` column) — this site's store
  // lives at /tickets, so new seat products land at
  // /tickets/p/<seatProductSlug()> instead of failing bulk import with
  // "Product page not found."
  squarespaceProductPage: 'tickets',

  // One entry per performance day. sku must match a Show.sku_prefix in
  // Django.
  //
  // STAKEHOLDER DEMO: trimmed to the single TEST01 show generated by
  // backend/test_data/generate_show_test_data.mjs — restore the full
  // show list before going live.
  shows: [{ sku: 'TEST01', label: 'STAKEHOLDER DEMO — DO NOT BUY' }],

  // The real room: several distinct seating blocks (some rotated) plus
  // furniture, transcribed from SeatChart8222026.png (per-seat
  // type/label). This is a best-effort transcription — verify against the
  // physical venue before going live. Block names/ids below are the ones
  // the user assigned when reviewing the chart.
  //
  // Seat identity: every seat's `code` is derived from its block id + grid
  // position (not its type/label), so reassigning a seat's role later
  // (e.g. which physical seats are "Actor" seats) is just editing that
  // cell's A()/G()/D()/C()/N() in place below — no effect on sold-seat
  // tracking.
  venue: {
    width: 926,
    height: 842,
    contentOffsetX: 0,
    contentOffsetY: 1,

    walls: { x: 10, y: 10, w: 880, h: 780, rx: 12 },

    furniture: [
      { type: 'piano', x: 780, y: 213.5, w: 100, h: 150, label: 'Grand Piano' },
      { type: 'table', x: 420, y: 171.5, w: 70, h: 130, label: 'Lectern', podium: { w: 30, h: 30 } }
    ],

    blocks: [
      // Back Bleachers — tall, 4 seats across, 11 rows, split by a
      // furniture gap (row 6) between the upper and lower halves.
      {
        id: 'BACK', name: 'Back Bleachers',
        x: 390, y: 500, rotation: -90,
        labelPos: 'top',
        cellSize: 32, gap: 6,
        grid: [
          [A(), D('PA'), D('PA'), A()],
          [D('PA'), G(), G(), C('DC')],
          [G(), G(), G(), D('DC')],
          [G(), G(), G(), G()],
          [G(), G(), G(), G()],
          [_, _, _, A()],
          [G(), A(), N('LU'), A()],
          [G(), A(), D('IL'), G()],
          [G(), N('MC'), G(), G()],
          [G(), G(), G(), G()],
          [A(), D('OK'), D('OK'), A()]
        ]
      },

      // Left Bleachers — two pairs of columns split by a center aisle
      // (col index 2 stays empty except for one front-row seat).
      {
        id: 'LEFTBLEACHERS', name: 'Left Bleachers',
        labelPos: 'top',
        x: 43, y: 486.5, rotation: -90,
        cellSize: 32, gap: 6,
        grid: [
          [C('AK'), A(), A(), D('KY'), D('KY')],
          [G(), C('PH'), _, A(), A()],
          [G(), C('VIR'), _, D('MO'), D('MO')],
          [A(), D('TN'), _, C('HI'), G()]
        ]
      },

      // Left Aisle — freestanding block below Left Bleachers.
      {
        id: 'LEFTAISLE', name: 'Left Aisle',
        labelPos: 'top',
        x: 275, y: 380, rotation: -90,
        cellSize: 32, gap: 6,
        grid: [
          [A(), D('VA'), A(), A()],
          [G(), G(), C('WV'), N('BR')],
          [C('TX'), D('MS'), G(), D('SC')],
          [A(), A(), A(), A()]
        ]
      },

      // Right Aisle — separated from Left Aisle by a walkway gap.
      {
        id: 'RIGHTAISLE', name: 'Right Aisle',
        labelPos: 'top',
        x: 490, y: 380, rotation: -90,
        cellSize: 32, gap: 6,
        grid: [
          [C('MD'), A(), D('NY'), _],
          [G(), G(), D('NY'), D('NY')],
          [G(), C('NJ'), C('VT'), A()],
          [C('NH'), D('MA'), A(), A()]
        ]
      },

      // Right Bleachers — mirrors Left Bleachers' aisle layout, plus one
      // isolated far-right column (col index 5, only rows 1 and 4).
      {
        id: 'RIGHTBLEACHERS', name: 'Right Bleachers',
        labelOffsetY: -42,
        labelPos: 'top',
        x: 693, y: 486.5, rotation: -90,
        cellSize: 32, gap: 6,
        grid: [
          [A(), A(), _, C('RI'), D('FL')],
          [D('CA'), A(), _, A(), G(),],
          [A(), D('CA'), _, G(), D('FL'),],
          [C('OR'), G(), A(), G(), C('WA')]
        ]
      },
      {
        id: 'RIGHTBLEACHERSISO', name: 'Right Bleacher — Floor Seats',
        x: 711, y: 416.5, rotation: 0,
        cellSize: 32, gap: 10,
        showFrame: false, // no section border/label — just 3 loose seats
        grid: [
          [G(), A()]
        ]
      },

      // Right-side blocks — rotated to follow the room's angled wall,
      // each paired with a small satellite block of isolated seats that
      // sit in front of its platform in the reference chart.
      {
        id: 'LEFTSTAGE', name: 'Left Stage',
        labelPos: 'top',
        labelOffsetX: -25,
        labelOffsetY: 45,
        // labelRotation: readable equivalent of this block's rotation
        // (rotation mod 180, mapped into -90..90) so the label reads
        // left-to-right while staying visually aligned to the seating rows.
        labelRotation: -30,
        x: 184, y: 90.5, rotation: -120,
        cellSize: 34, gap: 6,
        grid: [
          [G(), A()],
          [A(), C('MT')],
          [C('NM'), C('NV')],
          [G(), G()]
        ]
      },
      {
        id: 'LEFTSTAGEISO', name: 'Left Stage — Front Seats',
        x: 203, y: 216.5, rotation: -30,
        cellSize: 32, gap: 18,
        showFrame: false, // no section border/label — just 3 loose seats
        grid: [
          [C('CZ'), D('UT'), G()]
        ]
      },
      {
        id: 'CENTERSTAGE', name: 'Center Stage',
        labelPos: 'top',
        x: 419, y: 41.5, rotation: -90,
        cellSize: 34, gap: 6,
        grid: [
          [A(), A()],
          [N('MUR'), D('MI')],
          [C('WI'), D('ND')],
          [A(), A()]
        ]
      },
      // Two lone actor seats flanking the Lectern, one on each side.
      {
        id: 'LECTERNL', name: 'Lectern — Left',
        x: 380, y: 250, rotation: -90,
        cellSize: 34, gap: 6,
        showFrame: false,
        grid: [[A()]]
      },
      {
        id: 'LECTERNR', name: 'Lectern — Right',
        x: 497, y: 250, rotation: -90,
        cellSize: 34, gap: 6,
        showFrame: false,
        grid: [[A()]]
      },
      // Right Stage platform: 4 seats in the front row, 3 in the back row.
      // labelPos: 'top' centers the section label over the block's top
      // (short) edge instead of the default top-right corner — the
      // default reads awkwardly here because of this block's rotation.
      // labelRotation: readable equivalent of this block's rotation
      // (rotation mod 180, mapped into -90..90) so the label reads
      // left-to-right while staying visually aligned to the seating rows.
      {
        id: 'RIGHTSTAGE', name: 'Right \n Stage',
        labelPos: 'top',
        labelOffsetX: 40,
        labelOffsetY: 57,
        labelRotation: 35,
        x: 613, y: 130.5, rotation: -145,
        cellSize: 34, gap: 6,
        grid: [
          [D('IA'), D('IA'), C('MN'), G()],
          [A(), D('MN'), A(), G()]
        ]
      },
      {
        id: 'RIGHTSTAGEISO', name: 'Right Stage — Front Seats',
        x: 567, y: 209.5, rotation: -145,
        cellSize: 32, gap: 18,
        showFrame: false, // no section border/label — just 3 loose seats
        grid: [
          [D('SEC'), N('RAY'), G()]
        ]
      }
    ]
  }
}

// Flat code -> seat lookup, built once from the static venue layout above.
// code format: "<blockId><row+1>-<col+1>" (1-indexed, e.g. "L2-3") — the
// same friendly, block-scoped string shown to buyers as the seat's label,
// so the SKU/permalink a buyer sees matches the seat identity used
// everywhere else (holds, sold-seat tracking). Still fully derived from
// block id + grid position, not type or delegate state, so reassigning a
// cell's A()/G()/D() in place doesn't affect identity or sold-seat
// tracking. Delegate seats display their assigned state as a separate
// `label` field (see below) but keep this same position-based `code` as
// their actual identity, so two delegate seats can safely share a state
// without colliding.
function buildSeatIndex(venue) {
  const index = new Map()
  const seen = new Map()
  for (const block of venue.blocks) {
    block.grid.forEach((row, r) => {
      row.forEach((cell, c) => {
        if (!cell) return
        const code = seatCode(block.id, r, c)
        if (seen.has(code)) {
          throw new Error(
            `Duplicate seat code "${code}" — blocks ${seen.get(code)} and ${block.id} collide. ` +
              'Adjust block ids so seatCode() output stays unique.'
          )
        }
        seen.set(code, block.id)
        // Delegate seats display their state code; every other seat's
        // display label is just its code (already friendly/unique).
        const label = cell.label || code
        index.set(code, { ...cell, label, code })
      })
    })
  }
  return index
}

export const SEAT_INDEX = buildSeatIndex(CONFIG.venue)

export function seatCode(blockId, row, col) {
  return `${blockId}${row + 1}-${col + 1}`
}
